<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_Card Number</name>
   <tag></tag>
   <elementGuidId>5c2d6f79-8500-4bb7-8196-295f97459eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-cell.mat-cell.cdk-cell.cdk-column-Expiry.mat-column-Expiry.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new card'])[1]/preceding::mat-cell[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;4/2082&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-cell</value>
      <webElementGuid>bd7c4a77-a918-4bf1-947b-de81227293a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>0673577e-3ace-4da3-9386-9da4de5acbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20%</value>
      <webElementGuid>1858681c-be67-4360-b36d-fab9df3cc1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-Expiry mat-column-Expiry ng-star-inserted</value>
      <webElementGuid>a9b9c87d-57d1-4ef7-a4f6-1348c5b61c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4/2082</value>
      <webElementGuid>71801011-a0fc-4777-b852-1446561b7db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;mat-app-background bluegrey-lightgreen-theme&quot;]/app-root[1]/div[@class=&quot;mat-typography&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-star-inserted&quot;]/app-saved-payment-methods[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator mat-own-card mat-elevation-z6&quot;]/app-payment-method[1]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/mat-table[@class=&quot;mat-table cdk-table&quot;]/mat-row[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-Expiry mat-column-Expiry ng-star-inserted&quot;]</value>
      <webElementGuid>c173f802-52d3-454c-9a17-bc72fe8998c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fskfms'])[1]/following::mat-cell[1]</value>
      <webElementGuid>095d4094-2094-434d-a064-9e73bfa4b9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='************3224'])[1]/following::mat-cell[2]</value>
      <webElementGuid>913a4e45-5e55-46fb-9108-63479834b896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new card'])[1]/preceding::mat-cell[2]</value>
      <webElementGuid>722b2ba9-0a79-451a-8004-91fe39903d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a credit or debit card'])[1]/preceding::mat-cell[2]</value>
      <webElementGuid>f1837afc-cf0c-4d5f-8afe-78b80cc8ce0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4/2082']/parent::*</value>
      <webElementGuid>9ea1aff7-e4f7-4126-b510-40a8db388069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[3]</value>
      <webElementGuid>54c7398f-22cd-4a32-9eb3-d9c29e8d1c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-cell[(text() = '4/2082' or . = '4/2082')]</value>
      <webElementGuid>70499b49-1b72-47e3-b6af-f7d1b0d6dc57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
